tnqsoft_admin:
    resource: "@TnqsoftAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

tnqsoft_user:
    resource: "@TnqsoftUserBundle/Controller/"
    type:     annotation
    prefix:   /

tnqsoft_material:
    resource: "@TnqsoftMaterialBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
