services:
#    tnqsoft_user.example:
#        class: Tnqsoft\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    tnqsoft_user.validator.user_email_existed:
        class:  Tnqsoft\UserBundle\Validator\Constraints\UserEmailExistedValidator
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: validator.constraint_validator, alias: userEmailExisted }
